import { StateRecord } from "./types";

export const MX_STATES: StateRecord[] = [
  {
    code: "AGU",
    name: "Aguascalientes",
    postalRanges: [[20000, 20999]],
    cities: ["Aguascalientes", "Jesús María", "Calvillo", "Rincón de Romos", "Pabellón de Arteaga", "San Francisco de los Romo", "Asientos", "Tepezalá"],
  },
  {
    code: "BCN",
    name: "Baja California",
    postalRanges: [[21000, 22999]],
    cities: ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Rosarito", "San Quintín"],
  },
  {
    code: "BCS",
    name: "Baja California Sur",
    postalRanges: [[23000, 23999]],
    cities: ["La Paz", "Los Cabos", "San José del Cabo", "Cabo San Lucas", "Comondú", "Loreto", "Mulegé"],
  },
  {
    code: "CAM",
    name: "Campeche",
    postalRanges: [[24000, 24999]],
    cities: ["Campeche", "Ciudad del Carmen", "Champotón", "Escárcega", "Calkiní", "Hecelchakán", "Hopelchén"],
  },
  {
    code: "CHP",
    name: "Chiapas",
    postalRanges: [[29000, 30999]],
    cities: ["Tuxtla Gutiérrez", "San Cristóbal de las Casas", "Tapachula", "Comitán de Domínguez", "Chiapa de Corzo", "Palenque", "Ocosingo", "Villaflores"],
  },
  {
    code: "CHH",
    name: "Chihuahua",
    postalRanges: [[31000, 33999]],
    cities: ["Chihuahua", "Ciudad Juárez", "Delicias", "Cuauhtémoc", "Parral", "Nuevo Casas Grandes", "Camargo", "Jiménez"],
  },
  {
    code: "CMX",
    name: "Ciudad de México",
    postalRanges: [[1000, 16999]],
    cities: [
      "Álvaro Obregón",
      "Azcapotzalco",
      "Benito Juárez",
      "Coyoacán",
      "Cuajimalpa de Morelos",
      "Cuauhtémoc",
      "Gustavo A. Madero",
      "Iztacalco",
      "Iztapalapa",
      "La Magdalena Contreras",
      "Miguel Hidalgo",
      "Milpa Alta",
      "Tláhuac",
      "Tlalpan",
      "Venustiano Carranza",
      "Xochimilco",
    ],
  },
  {
    code: "COA",
    name: "Coahuila",
    postalRanges: [[25000, 27999]],
    cities: ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña", "Sabinas", "Ramos Arizpe", "Matamoros"],
  },
  {
    code: "COL",
    name: "Colima",
    postalRanges: [[28000, 28999]],
    cities: ["Colima", "Manzanillo", "Villa de Álvarez", "Tecomán", "Comala", "Armería", "Cuauhtémoc"],
  },
  {
    code: "DUR",
    name: "Durango",
    postalRanges: [[34000, 35999]],
    cities: ["Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro", "El Salto", "Canatlán", "Nuevo Ideal"],
  },
  {
    code: "GUA",
    name: "Guanajuato",
    postalRanges: [[36000, 38999]],
    cities: ["León", "Guanajuato", "Irapuato", "Celaya", "Salamanca", "San Miguel de Allende", "Silao", "Dolores Hidalgo", "San Francisco del Rincón", "Pénjamo"],
  },
  {
    code: "GRO",
    name: "Guerrero",
    postalRanges: [[39000, 41999]],
    cities: ["Acapulco de Juárez", "Chilpancingo", "Iguala", "Zihuatanejo", "Taxco de Alarcón", "Tlapa de Comonfort", "Ometepec"],
  },
  {
    code: "HID",
    name: "Hidalgo",
    postalRanges: [[42000, 43999]],
    cities: ["Pachuca de Soto", "Tulancingo", "Tula de Allende", "Tizayuca", "Huejutla de Reyes", "Ixmiquilpan", "Actopan", "Apan"],
  },
  {
    code: "JAL",
    name: "Jalisco",
    postalRanges: [[44000, 49999]],
    cities: ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Tlajomulco de Zúñiga", "Puerto Vallarta", "Lagos de Moreno", "Ocotlán", "Tepatitlán de Morelos", "Zapotlán el Grande"],
  },
  {
    code: "MEX",
    name: "Estado de México",
    postalRanges: [[50000, 57999]],
    cities: ["Toluca", "Ecatepec de Morelos", "Nezahualcóyotl", "Naucalpan de Juárez", "Tlalnepantla de Baz", "Chimalhuacán", "Cuautitlán Izcalli", "Atizapán de Zaragoza", "Metepec", "Texcoco", "Valle de Chalco", "Huixquilucan"],
  },
  {
    code: "MIC",
    name: "Michoacán",
    postalRanges: [[58000, 61999]],
    cities: ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Apatzingán", "Zitácuaro", "La Piedad", "Pátzcuaro", "Sahuayo"],
  },
  {
    code: "MOR",
    name: "Morelos",
    postalRanges: [[62000, 62999]],
    cities: ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Yautepec", "Zacatepec", "Emiliano Zapata", "Puente de Ixtla"],
  },
  {
    code: "NAY",
    name: "Nayarit",
    postalRanges: [[63000, 63999]],
    cities: ["Tepic", "Bahía de Banderas", "Santiago Ixcuintla", "Compostela", "Tuxpan", "Ixtlán del Río", "Acaponeta"],
  },
  {
    code: "NLE",
    name: "Nuevo León",
    postalRanges: [[64000, 67999]],
    cities: ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "General Escobedo", "Santa Catarina", "San Pedro Garza García", "Juárez", "Linares", "Montemorelos"],
  },
  {
    code: "OAX",
    name: "Oaxaca",
    postalRanges: [[68000, 71999]],
    cities: ["Oaxaca de Juárez", "Salina Cruz", "Juchitán de Zaragoza", "Tuxtepec", "Huajuapan de León", "Santa Cruz Xoxocotlán", "Puerto Escondido", "Tehuantepec"],
  },
  {
    code: "PUE",
    name: "Puebla",
    postalRanges: [[72000, 75999]],
    cities: ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "San Pedro Cholula", "Amozoc", "Teziutlán", "Huauchinango", "Izúcar de Matamoros"],
  },
  {
    code: "QUE",
    name: "Querétaro",
    postalRanges: [[76000, 76999]],
    cities: ["Querétaro", "San Juan del Río", "Corregidora", "El Marqués", "Tequisquiapan", "Cadereyta de Montes", "Jalpan de Serra"],
  },
  {
    code: "ROO",
    name: "Quintana Roo",
    postalRanges: [[77000, 77999]],
    cities: ["Cancún", "Chetumal", "Playa del Carmen", "Cozumel", "Tulum", "Isla Mujeres", "Bacalar", "Felipe Carrillo Puerto"],
  },
  {
    code: "SLP",
    name: "San Luis Potosí",
    postalRanges: [[78000, 79999]],
    cities: ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala", "Rioverde", "Tamazunchale", "Ciudad Fernández"],
  },
  {
    code: "SIN",
    name: "Sinaloa",
    postalRanges: [[80000, 82999]],
    cities: ["Culiacán", "Mazatlán", "Los Mochis", "Guasave", "Guamúchil", "Navolato", "El Fuerte", "Escuinapa"],
  },
  {
    code: "SON",
    name: "Sonora",
    postalRanges: [[83000, 85999]],
    cities: ["Hermosillo", "Ciudad Obregón", "Nogales", "San Luis Río Colorado", "Navojoa", "Guaymas", "Agua Prieta", "Puerto Peñasco"],
  },
  {
    code: "TAB",
    name: "Tabasco",
    postalRanges: [[86000, 86999]],
    cities: ["Villahermosa", "Cárdenas", "Comalcalco", "Macuspana", "Huimanguillo", "Tenosique", "Paraíso", "Emiliano Zapata"],
  },
  {
    code: "TAM",
    name: "Tamaulipas",
    postalRanges: [[87000, 89999]],
    cities: ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico", "Ciudad Victoria", "Ciudad Madero", "Altamira", "El Mante"],
  },
  {
    code: "TLA",
    name: "Tlaxcala",
    postalRanges: [[90000, 90999]],
    cities: ["Tlaxcala", "Apizaco", "Huamantla", "Chiautempan", "Zacatelco", "Calpulalpan", "Contla de Juan Cuamatzi", "San Pablo del Monte", "Tlaxco", "Santa Ana Chiautempan"],
  },
  {
    code: "VER",
    name: "Veracruz",
    postalRanges: [[91000, 96999]],
    cities: ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Poza Rica", "Minatitlán", "Orizaba", "Boca del Río", "Tuxpan", "San Andrés Tuxtla"],
  },
  {
    code: "YUC",
    name: "Yucatán",
    postalRanges: [[97000, 97999]],
    cities: ["Mérida", "Valladolid", "Progreso", "Tizimín", "Kanasín", "Umán", "Motul", "Ticul"],
  },
  {
    code: "ZAC",
    name: "Zacatecas",
    postalRanges: [[98000, 99999]],
    cities: ["Zacatecas", "Guadalupe", "Fresnillo", "Jerez", "Río Grande", "Sombrerete", "Calera", "Ojocaliente"],
  },
];
