import { StateRecord } from "./types";

export const US_STATES: StateRecord[] = [
  { code: "AL", name: "Alabama", postalRanges: [[35000, 36999]], cities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa", "Hoover", "Auburn", "Dothan"] },
  { code: "AK", name: "Alaska", postalRanges: [[99500, 99999]], cities: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan", "Wasilla", "Kenai"] },
  { code: "AZ", name: "Arizona", postalRanges: [[85000, 86599]], cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale", "Gilbert", "Tempe", "Yuma", "Flagstaff"] },
  { code: "AR", name: "Arkansas", postalRanges: [[71600, 72999]], cities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro", "Rogers", "Conway", "Bentonville"] },
  { code: "CA", name: "California", postalRanges: [[90000, 96199]], cities: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside", "Stockton", "Irvine", "Chula Vista"] },
  { code: "CO", name: "Colorado", postalRanges: [[80000, 81699]], cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Pueblo", "Boulder", "Greeley"] },
  { code: "CT", name: "Connecticut", postalRanges: [[6000, 6389], [6391, 6999]], cities: ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk", "Danbury", "New Britain"] },
  { code: "DE", name: "Delaware", postalRanges: [[19700, 19999]], cities: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna", "Milford", "Seaford"] },
  { code: "DC", name: "District of Columbia", postalRanges: [[20000, 20599]], cities: ["Washington"] },
  { code: "FL", name: "Florida", postalRanges: [[32000, 34999]], cities: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Port St. Lucie", "Tallahassee", "Fort Lauderdale", "Cape Coral", "Pembroke Pines", "Hollywood"] },
  { code: "GA", name: "Georgia", postalRanges: [[30000, 31999], [39800, 39999]], cities: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs", "Roswell", "Albany", "Marietta"] },
  { code: "HI", name: "Hawaii", postalRanges: [[96700, 96899]], cities: ["Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu", "Kaneohe", "Kahului", "Kona"] },
  { code: "ID", name: "Idaho", postalRanges: [[83200, 83899]], cities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell", "Coeur d'Alene", "Twin Falls"] },
  { code: "IL", name: "Illinois", postalRanges: [[60000, 62999]], cities: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield", "Elgin", "Peoria", "Champaign", "Waukegan", "Cicero"] },
  { code: "IN", name: "Indiana", postalRanges: [[46000, 47999]], cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Fishers", "Bloomington", "Hammond", "Gary", "Lafayette"] },
  { code: "IA", name: "Iowa", postalRanges: [[50000, 52899]], cities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo", "Council Bluffs", "Ames"] },
  { code: "KS", name: "Kansas", postalRanges: [[66000, 67999]], cities: ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence", "Shawnee", "Manhattan"] },
  { code: "KY", name: "Kentucky", postalRanges: [[40000, 42799]], cities: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Richmond", "Georgetown", "Florence"] },
  { code: "LA", name: "Louisiana", postalRanges: [[70000, 71499]], cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles", "Kenner", "Bossier City", "Monroe", "Alexandria"] },
  { code: "ME", name: "Maine", postalRanges: [[3900, 4999]], cities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford", "Augusta", "Scarborough"] },
  { code: "MD", name: "Maryland", postalRanges: [[20600, 21999]], cities: ["Baltimore", "Columbia", "Germantown", "Silver Spring", "Waldorf", "Glen Burnie", "Frederick", "Rockville", "Gaithersburg", "Annapolis"] },
  { code: "MA", name: "Massachusetts", postalRanges: [[1000, 2799], [5500, 5599]], cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "New Bedford", "Quincy", "Lynn", "Newton", "Somerville", "Framingham"] },
  { code: "MI", name: "Michigan", postalRanges: [[48000, 49999]], cities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint", "Dearborn", "Livonia", "Troy", "Kalamazoo"] },
  { code: "MN", name: "Minnesota", postalRanges: [[55000, 56799]], cities: ["Minneapolis", "St. Paul", "Rochester", "Duluth", "Bloomington", "Brooklyn Park", "Plymouth", "St. Cloud", "Eagan"] },
  { code: "MS", name: "Mississippi", postalRanges: [[38600, 39799]], cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian", "Tupelo", "Olive Branch"] },
  { code: "MO", name: "Missouri", postalRanges: [[63000, 65899]], cities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles"] },
  { code: "MT", name: "Montana", postalRanges: [[59000, 59999]], cities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena", "Kalispell"] },
  { code: "NE", name: "Nebraska", postalRanges: [[68000, 69399]], cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Hastings", "Norfolk"] },
  { code: "NV", name: "Nevada", postalRanges: [[88900, 89899]], cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City", "Elko", "Mesquite"] },
  { code: "NH", name: "New Hampshire", postalRanges: [[3000, 3899]], cities: ["Manchester", "Nashua", "Concord", "Derry", "Dover", "Rochester", "Salem", "Merrimack"] },
  { code: "NJ", name: "New Jersey", postalRanges: [[7000, 8999]], cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge", "Trenton", "Camden", "Clifton", "Passaic", "Union City"] },
  { code: "NM", name: "New Mexico", postalRanges: [[87000, 88499]], cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell", "Farmington", "Clovis", "Hobbs"] },
  { code: "NY", name: "New York", postalRanges: [[500, 599], [6390, 6390], [10000, 14999]], cities: ["New York", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica", "White Plains", "Hempstead"] },
  { code: "NC", name: "North Carolina", postalRanges: [[27000, 28999]], cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "High Point", "Concord"] },
  { code: "ND", name: "North Dakota", postalRanges: [[58000, 58899]], cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston", "Dickinson"] },
  { code: "OH", name: "Ohio", postalRanges: [[43000, 45999]], cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma", "Canton", "Youngstown", "Lorain"] },
  { code: "OK", name: "Oklahoma", postalRanges: [[73000, 74999]], cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton", "Edmond", "Moore", "Midwest City", "Enid"] },
  { code: "OR", name: "Oregon", postalRanges: [[97000, 97999]], cities: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Beaverton", "Bend", "Medford", "Springfield"] },
  { code: "PA", name: "Pennsylvania", postalRanges: [[15000, 19699]], cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Bethlehem", "Lancaster", "Harrisburg", "Altoona"] },
  { code: "RI", name: "Rhode Island", postalRanges: [[2800, 2999]], cities: ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket", "Newport"] },
  { code: "SC", name: "South Carolina", postalRanges: [[29000, 29999]], cities: ["Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville", "Summerville", "Myrtle Beach"] },
  { code: "SD", name: "South Dakota", postalRanges: [[57000, 57799]], cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell", "Pierre"] },
  { code: "TN", name: "Tennessee", postalRanges: [[37000, 38599]], cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin", "Jackson", "Johnson City"] },
  { code: "TX", name: "Texas", postalRanges: [[75000, 79999], [88500, 88599]], cities: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo", "Lubbock", "Garland", "Irving", "Amarillo", "McAllen", "Brownsville"] },
  { code: "UT", name: "Utah", postalRanges: [[84000, 84799]], cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy", "Ogden", "St. George", "Layton"] },
  { code: "VT", name: "Vermont", postalRanges: [[5000, 5499], [5600, 5999]], cities: ["Burlington", "South Burlington", "Rutland", "Essex Junction", "Barre", "Montpelier", "St. Albans"] },
  { code: "VA", name: "Virginia", postalRanges: [[22000, 24699]], cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Arlington"] },
  { code: "WA", name: "Washington", postalRanges: [[98000, 99499]], cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Renton", "Yakima", "Federal Way"] },
  { code: "WV", name: "West Virginia", postalRanges: [[24700, 26899]], cities: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling", "Martinsburg", "Fairmont", "Beckley"] },
  { code: "WI", name: "Wisconsin", postalRanges: [[53000, 54999]], cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Waukesha", "Oshkosh", "Eau Claire"] },
  { code: "WY", name: "Wyoming", postalRanges: [[82000, 83199]], cities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs", "Sheridan", "Jackson"] },
];
