import { StyleSheet, Platform, Dimensions } from "react-native";
import { PURPLE, PURPLE_DARK } from "./colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#FFFFFF" },
  centerScreen: {
    flex: 1,
    backgroundColor: "#F8FAFC",
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  authCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#FFFFFF",
    padding: 32,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  languageBox: { marginBottom: 20 },
  languageHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 6,
  },
  languageLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
  },
  languageToggle: {
    flexDirection: "row",
    backgroundColor: "#F3F4F6",
    borderRadius: 14,
    padding: 4,
  },
  languageOption: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  languageOptionActive: {
    backgroundColor: PURPLE,
  },
  languageOptionText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#4B5563",
  },
  languageOptionTextActive: {
    color: "#FFFFFF",
  },
  logoBox: {
    width: 64,
    height: 64,
    backgroundColor: PURPLE,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 24,
    shadowColor: PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  authTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
    textAlign: "center",
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: 24,
  },
  authInput: {
    width: "100%",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    fontSize: 16,
    color: "#111827",
    backgroundColor: "#FFFFFF",
  },
  mainButton: {
    width: "100%",
    backgroundColor: PURPLE,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PURPLE,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  mainButtonPressed: {
    transform: [{ scale: 0.98 }],
    backgroundColor: PURPLE_DARK,
  },
  mainButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 16,
  },
  secondaryLinkButton: {
    width: "100%",
    paddingVertical: 12,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  secondaryLinkText: {
    color: PURPLE,
    fontSize: 14,
    fontWeight: "800",
  },
  registerScreen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  registerContent: {
    padding: 24,
    paddingBottom: 40,
  },
  progressRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  progressBar: {
    flex: 1,
    height: 6,
    borderRadius: 999,
  },
  progressBarActive: {
    backgroundColor: PURPLE,
  },
  progressBarInactive: {
    backgroundColor: "#F3F4F6",
  },
  backGhost: {
    alignSelf: "flex-start",
    marginBottom: 16,
  },
  backButton: {
    alignSelf: "flex-start",
    padding: 10,
    backgroundColor: "#F1F5F9",
    borderRadius: 999,
    marginBottom: 16,
  },
  stepTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 8,
  },
  stepSubtitle: {
    fontSize: 16,
    color: "#6B7280",
    marginBottom: 24,
  },
  stepSubtitleSmall: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 24,
  },
  phoneRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  phoneRowNoMargin: {
    flexDirection: "row",
    gap: 8,
  },
  prefixBox: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  prefixText: {
    fontWeight: "800",
    color: "#4B5563",
  },
  phoneInput: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "#F1F5F9",
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  stepCenter: {
    alignItems: "center",
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FAF5FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  stepTitleCenter: {
    fontSize: 28,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 8,
    textAlign: "center",
  },
  stepSubtitleCenter: {
    fontSize: 16,
    color: "#6B7280",
    marginBottom: 24,
    textAlign: "center",
  },
  otpRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  otpInput: {
    width: 46,
    height: 52,
    borderWidth: 2,
    borderColor: "#F1F5F9",
    borderRadius: 14,
    textAlign: "center",
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
  },
  pinInput: {
    width: "100%",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: "#F1F5F9",
    borderRadius: 18,
    fontSize: 28,
    fontWeight: "800",
    textAlign: "center",
    color: "#111827",
    marginBottom: 24,
    letterSpacing: 10,
  },
  step4Container: {
    paddingBottom: 16,
  },
  formField: {
    marginBottom: 12,
  },
  formLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: "#9CA3AF",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginLeft: 4,
    marginBottom: 6,
  },
  formInput: {
    width: "100%",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    fontSize: 14,
    color: "#111827",
  },
  uploadBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  uploadIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#FAF5FF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  uploadTextWrap: {
    flex: 1,
  },
  uploadPrimaryText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  uploadSecondaryText: {
    fontSize: 12,
    color: PURPLE,
    fontWeight: "700",
    marginTop: 2,
  },
  row2: {
    flexDirection: "row",
    gap: 12,
  },
  row3: {
    flexDirection: "row",
    gap: 12,
  },
  flex1: {
    flex: 1,
  },
  smallCol: {
    width: "28%",
  },
  largeCol: {
    flex: 1,
  },
  groupBoxGray: {
    backgroundColor: "#F8FAFC",
    borderRadius: 18,
    padding: 16,
  },
  groupBoxPurple: {
    backgroundColor: "#FAF5FF",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E9D5FF",
  },
  dashboardScreen: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  dashboardSafeTop: {
    backgroundColor: "#FFFFFF",
  },
  dashboardHeader: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  kicker: {
    fontSize: 10,
    color: "#9CA3AF",
    fontWeight: "800",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  balance: {
    fontSize: 24,
    fontWeight: "900",
    color: "#111827",
    marginTop: 2,
  },
  iconButton: {
    padding: 12,
    backgroundColor: "#F1F5F9",
    borderRadius: 18,
  },
  iconButtonPressed: {
    transform: [{ scale: 0.95 }],
  },
  dashboardContent: {
    padding: 24,
    paddingBottom: 40,
  },
  virtualCard: {
    width: "95%",
    aspectRatio: 1.586,
    borderRadius: 32,
    padding: 20,
    overflow: "hidden",
    marginBottom: 16,
  },
  virtualCardOn: {
    backgroundColor: PURPLE,
    shadowColor: PURPLE,
    shadowOpacity: 0.4,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  virtualCardOff: {
    backgroundColor: "#94A3B8",
  },
  virtualCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    backgroundColor: "rgba(15,23,42,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  virtualCardOverlayText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 8,
    textTransform: "uppercase",
  },
  virtualCardInner: {
    flex: 1,
    justifyContent: "space-between",
    zIndex: 10,
  },
  virtualCardNumber: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
    letterSpacing: 4,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }),
  },
  virtualCardName: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  cardToggleRow: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  cardToggleText: {
    fontSize: 14,
    color: "#374151",
    fontWeight: "800",
  },
  switchTrack: {
    width: 48,
    height: 28,
    borderRadius: 999,
    position: "relative",
  },
  switchThumb: {
    position: "absolute",
    top: 4,
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 12,
  },
  activityRow: {
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  activityLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  activityIcon: {
    padding: 10,
    borderRadius: 12,
  },
  activityLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  activityAmount: {
    fontSize: 14,
    fontWeight: "900",
    marginLeft: 12,
  },
  kycScreen: {
    flex: 1,
    backgroundColor: "#0F172A",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  kycLogo: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  kycLogoText: {
    color: PURPLE,
    fontSize: 40,
    fontWeight: "900",
    fontStyle: "italic",
  },
  kycTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 12,
    textAlign: "center",
  },
  kycSubtitle: {
    fontSize: 16,
    color: "#94A3B8",
    marginBottom: 28,
    textAlign: "center",
  },
  kycButton: {
    backgroundColor: "#FFFFFF",
  },
  kycButtonText: {
    color: "#111827",
  },
  pageScreen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  pageContent: {
    padding: 24,
    paddingBottom: 40,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 8,
  },
  pageSubtitle: {
    fontSize: 15,
    color: "#6B7280",
    marginBottom: 24,
  },
  statusCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  statusIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "#FAF5FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  statusTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#111827",
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 16,
    lineHeight: 20,
  },
  statusInfoBox: {
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    padding: 14,    
  },
  statusInfoLabel: {
    fontSize: 11,
    color: "#9CA3AF",
    fontWeight: "900",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  statusInfoValue: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "700",
  },
  centerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  successBanner: {
    backgroundColor: "#F0FDF4",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#BBF7D0",
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  successTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#166534",
    marginBottom: 4,
  },
  successText: {
    fontSize: 13,
    color: "#166534",
    lineHeight: 18,
  },
  walletCard: {
    backgroundColor: PURPLE,
    borderRadius: 24,
    padding: 20,
    marginBottom: 15,
  },
  walletRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  walletTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  walletIdText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 18,
  },
  walletFundsLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  walletFundsValue: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "900",
  },
  transferCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    padding: 18,
  },
  transferSuccessBox: {
    marginTop: 12,
    backgroundColor: "#F0FDF4",
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  transferSuccessText: {
    color: "#166534",
    fontWeight: "700",
    fontSize: 13,
  },
  filterWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  filterChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#F3F4F6",
  },
  filterChipActive: {
    backgroundColor: PURPLE,
  },
  filterChipText: {
    color: "#4B5563",
    fontWeight: "700",
    fontSize: 13,
  },
  filterChipTextActive: {
    color: "#FFFFFF",
  },
  operationBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  operationBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#111827",
  },
  operationDate: {
    fontSize: 11,
    color: "#9CA3AF",
    fontWeight: "700",
    marginTop: 4,
  },
  emptyCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 18,
    padding: 18,
    alignItems: "center",
  },
  emptyCardText: {
    color: "#6B7280",
    fontWeight: "700",
  },
  profileAvatarWrap: {
    alignItems: "center",
    marginBottom: 20,
  },
  profileAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: "#E2E8F0",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    borderColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15,23,42,0.60)",
  },
  drawer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 288,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: -6, height: 0 },
    elevation: 12,
  },
  drawerContent: {
    flex: 1,
    padding: 24,
  },
  drawerClose: {
    alignSelf: "flex-start",
    padding: 10,
    backgroundColor: "#F1F5F9",
    borderRadius: 14,
    marginBottom: 24,
  },
  drawerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 8,
  },
  drawerItemText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#374151",
  },
  drawerLogoutText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#EF4444",
  },
  spacer: {
    flex: 1,
  },
  stack12: {
    gap: 12,
  },
  stack16: {
    gap: 16,
  },
  stack24: {
    gap: 24,
  },
  beneficiaryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  beneficiaryCardSelected: {
    backgroundColor: PURPLE,
    borderColor: PURPLE,
  },
  beneficiaryIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#FAF5FF",
    alignItems: "center",
    justifyContent: "center",
  },
  beneficiaryName: {
    fontSize: 14,
    fontWeight: "900",
    color: "#111827",
  },
  beneficiaryNameSelected: {
    color: "#FFFFFF",
  },
  beneficiaryMeta: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6B7280",
    marginTop: 2,
  },
  beneficiaryMetaSelected: {
    color: "rgba(255,255,255,0.8)",
  },
  errorBox: {
    marginTop: 12,
    backgroundColor: "#FEF2F2",
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    color: "#DC2626",
    fontWeight: "700",
    fontSize: 13,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 24,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  row: {
    marginBottom: 18,
  },
  label: {
    fontSize: 14,
    color: "#6B7280",
    marginBottom: 4,
  },
  value: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
  },
  cancelButton: {
    marginTop: 30,
    backgroundColor: "#DC2626",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
  },

  cancelButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },

  cardSlide: {
  width: Dimensions.get("window").width - 40,
  marginRight: 0,
},

cardTypeLabel: {
  fontSize: 14,
  fontWeight: "600",
  marginBottom: 8,
  color: "#111827",
},

dotsRow: {
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
  gap: 6,
  marginTop: 12,
  marginBottom: 16,
},

dot: {
  width: 8,
  height: 8,
  borderRadius: 4,
  backgroundColor: "#D1D5DB",
},

dotActive: {
  width: 18,
  backgroundColor: PURPLE,
},
inactiveCardMessage: {
  backgroundColor: "#FEF3C7",
  borderRadius: 14,
  padding: 14,
  marginBottom: 14,
},

inactiveCardTitle: {
  fontSize: 14,
  fontWeight: "700",
  color: "#92400E",
  marginBottom: 4,
},

activateNowText: {
  fontSize: 14,
  fontWeight: "700",
  color: PURPLE,
},

successCardMessage: {
  backgroundColor: "#DCFCE7",
  borderRadius: 14,
  padding: 14,
  marginBottom: 14,
},

successCardText: {
  fontSize: 14,
  fontWeight: "700",
  color: "#166534",
},

modalOverlay: {
  flex: 1,
  backgroundColor: "rgba(0,0,0,0.45)",
  justifyContent: "center",
  alignItems: "center",
  padding: 24,
},

modalContent: {
  width: "100%",
  backgroundColor: "#fff",
  borderRadius: 20,
  padding: 20,
},

modalTitle: {
  fontSize: 18,
  fontWeight: "700",
  color: "#111827",
  marginBottom: 6,
},

modalSubtitle: {
  fontSize: 14,
  color: "#6B7280",
  marginBottom: 16,
},

secureCodeInput: {
  height: 52,
  borderWidth: 1,
  borderColor: "#D1D5DB",
  borderRadius: 12,
  paddingHorizontal: 16,
  fontSize: 16,
  letterSpacing: 6,
  textAlign: "center",
  marginBottom: 16,
},

activateButton: {
  height: 48,
  borderRadius: 12,
  backgroundColor: PURPLE,
  alignItems: "center",
  justifyContent: "center",
  marginBottom: 14,
},

activateButtonDisabled: {
  opacity: 0.5,
},

activateButtonText: {
  color: "#fff",
  fontSize: 15,
  fontWeight: "700",
},

cancelText: {
  textAlign: "center",
  color: "#6B7280",
  fontSize: 14,
  fontWeight: "600",
},

selectField: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  width: "100%",
  paddingVertical: 12,
  paddingHorizontal: 14,
  borderRadius: 14,
  backgroundColor: "#F8FAFC",
},
selectFieldText: {
  fontSize: 14,
  color: "#111827",
},
selectFieldPlaceholder: {
  fontSize: 14,
  color: "#9CA3AF",
},
pickerOverlay: {
  flex: 1,
  backgroundColor: "rgba(17, 24, 39, 0.5)",
  justifyContent: "flex-end",
},
modalSheet: {
  backgroundColor: "#FFFFFF",
  borderTopLeftRadius: 24,
  borderTopRightRadius: 24,
  padding: 20,
  maxHeight: "70%",
},
pickerTitle: {
  fontSize: 16,
  fontWeight: "800",
  color: "#111827",
  marginBottom: 12,
},
modalScroll: {
  marginBottom: 8,
},
modalOption: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  paddingVertical: 14,
  borderBottomWidth: 1,
  borderBottomColor: "#F1F5F9",
},
modalOptionText: {
  fontSize: 15,
  color: "#111827",
},

fieldErrorText: {
  color: "#EF4444",
  fontSize: 12,
  marginTop: 4,
  marginLeft: 4,
},

fieldHintText: {
  color: "#6B7280",
  fontSize: 12,
  marginTop: 4,
  marginLeft: 4,
},
prefixBoxRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 4,
},

documentCard: {
  borderWidth: 1,
  borderColor: "#E5E7EB",
  borderRadius: 16,
  backgroundColor: "#FFFFFF",
  padding: 12,
  gap: 8,
},
documentCardLabel: {
  fontSize: 13,
  fontWeight: "700",
  color: "#374151",
},
documentRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 12,
},
documentEmptyRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 12,
},
documentThumb: {
  width: 64,
  height: 64,
  borderRadius: 12,
  backgroundColor: "#F1F5F9",
},
documentThumbFile: {
  alignItems: "center",
  justifyContent: "center",
  gap: 2,
},
documentThumbEmpty: {
  width: 64,
  height: 64,
  borderRadius: 12,
  backgroundColor: "#F5F3FF",
  alignItems: "center",
  justifyContent: "center",
  borderWidth: 1,
  borderColor: "#DDD6FE",
  borderStyle: "dashed",
},
documentThumbBadge: {
  fontSize: 10,
  fontWeight: "800",
  color: PURPLE,
},
documentInfo: {
  flex: 1,
  gap: 2,
},
documentName: {
  fontSize: 14,
  fontWeight: "600",
  color: "#111827",
},
documentMeta: {
  fontSize: 12,
  color: "#6B7280",
},
documentStatusRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 6,
  marginTop: 2,
},
documentOkText: {
  fontSize: 12,
  color: "#16A34A",
  fontWeight: "600",
},
documentErrorText: {
  flex: 1,
  fontSize: 12,
  color: "#EF4444",
},
documentActions: {
  gap: 8,
},
documentActionButton: {
  width: 34,
  height: 34,
  borderRadius: 10,
  backgroundColor: "#F8FAFC",
  alignItems: "center",
  justifyContent: "center",
},
documentRetry: {
  alignSelf: "flex-start",
  paddingVertical: 6,
  paddingHorizontal: 10,
  borderRadius: 10,
  backgroundColor: "#FEF2F2",
},
documentRetryText: {
  fontSize: 12,
  fontWeight: "700",
  color: "#B91C1C",
},

verifyingWrap: {
  alignItems: "center",
  justifyContent: "center",
  paddingHorizontal: 24,
  paddingVertical: 90,
  gap: 14,
},
credentialsCard: {
  width: "100%",
  borderWidth: 1,
  borderColor: "#E5E7EB",
  borderRadius: 18,
  backgroundColor: "#F8FAFC",
  padding: 16,
  gap: 14,
},
credentialsLabel: {
  fontSize: 12,
  fontWeight: "700",
  color: "#6B7280",
  textTransform: "uppercase",
},
credentialsValue: {
  fontSize: 17,
  fontWeight: "700",
  color: "#111827",
},
credentialsValueRow: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 12,
},
credentialsToggleText: {
  fontSize: 13,
  fontWeight: "700",
  color: PURPLE,
},
successIconCircle: {
  width: 78,
  height: 78,
  borderRadius: 39,
  backgroundColor: "#ECFDF5",
  alignItems: "center",
  justifyContent: "center",
},
fieldHighlighted: {
  borderWidth: 2,
  borderColor: "#EF4444",
  backgroundColor: "#FEF2F2",
},
selectFieldDisabled: {
  backgroundColor: "#F1F5F9",
  opacity: 0.6,
},
selectFieldDisabledText: {
  fontSize: 14,
  color: "#9CA3AF",
},
searchRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 8,
  paddingHorizontal: 12,
  paddingVertical: 10,
  borderRadius: 12,
  backgroundColor: "#F8FAFC",
  marginBottom: 8,
},
searchInput: {
  flex: 1,
  fontSize: 14,
  color: "#111827",
  paddingVertical: 0,
},
emptyResultsText: {
  paddingVertical: 24,
  textAlign: "center",
  color: "#6B7280",
  fontSize: 14,
},
formBanner: {
  flexDirection: "row",
  alignItems: "center",
  gap: 8,
  padding: 12,
  borderRadius: 14,
  backgroundColor: "#FEF2F2",
  borderWidth: 1,
  borderColor: "#FECACA",
},
formBannerText: {
  flex: 1,
  color: "#B91C1C",
  fontSize: 13,
  lineHeight: 18,
},

otpActionsRow: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  gap: 16,
  marginBottom: 8,
},
resendText: {
  fontSize: 13,
  color: "#6B7280",
},
resendLink: {
  fontSize: 13,
  color: PURPLE,
  fontWeight: "800",
},
pasteLink: {
  fontSize: 13,
  color: PURPLE,
  fontWeight: "800",
},

passcodeFieldWrap: {
  width: "100%",
  position: "relative",
  marginBottom: 8,
},
eyeToggle: {
  position: "absolute",
  right: 16,
  top: 0,
  bottom: 0,
  justifyContent: "center",
},

forgotLink: {
  alignSelf: "center",
  marginTop: 4,
},
forgotLinkText: {
  fontSize: 13,
  color: PURPLE,
  fontWeight: "700",
},

infoBox: {
  backgroundColor: "#FAF5FF",
  borderRadius: 16,
  padding: 16,
  marginBottom: 24,
},
infoBoxText: {
  fontSize: 14,
  color: "#4B5563",
  lineHeight: 20,
},
});