import { StyleSheet, Platform, Dimensions } from "react-native";
import {
  DANGER,
  DANGER_SOLID,
  DANGER_BORDER,
  DANGER_SURFACE,
  GLASS_BORDER,
  GLASS_SURFACE,
  GLASS_SURFACE_STRONG,
  PURPLE,
  PURPLE_DEEP,
  SCRIM,
  SCRIM_SOFT,
  SUCCESS,
  SUCCESS_BORDER,
  SUCCESS_SURFACE,
  TEXT_DISABLED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  VIOLET,
  VIOLET_BORDER,
  VIOLET_SURFACE,
  VIOLET_TEXT,
  WARNING,
  WARNING_SURFACE,
} from "./colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "transparent" },
  centerScreen: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  authCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: GLASS_SURFACE,
    padding: 32,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  languageBox: { marginBottom: 20 },
  languageHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 6,
  },
  languageLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: TEXT_SECONDARY,
  },
  languageToggle: {
    flexDirection: "row",
    backgroundColor: GLASS_SURFACE,
    borderRadius: 14,
    padding: 4,
  },
  languageOption: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  languageOptionActive: {
    backgroundColor: VIOLET,
  },
  languageOptionText: {
    fontSize: 13,
    fontWeight: "700",
    color: TEXT_SECONDARY,
  },
  languageOptionTextActive: {
    color: TEXT_PRIMARY,
  },
  logoBox: {
    width: 64,
    height: 64,
    backgroundColor: VIOLET,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 24,
    shadowColor: PURPLE,
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  authTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: TEXT_PRIMARY,
    textAlign: "center",
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    textAlign: "center",
    marginBottom: 24,
  },
  authInput: {
    width: "100%",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    fontSize: 16,
    color: TEXT_PRIMARY,
    backgroundColor: GLASS_SURFACE,
  },
  mainButton: {
    width: "100%",
    backgroundColor: VIOLET,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PURPLE,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  mainButtonPressed: {
    transform: [{ scale: 0.98 }],
    backgroundColor: PURPLE_DEEP,
  },
  mainButtonText: {
    color: TEXT_PRIMARY,
    fontWeight: "800",
    fontSize: 16,
  },
  secondaryLinkButton: {
    width: "100%",
    paddingVertical: 12,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  secondaryLinkText: {
    color: VIOLET_TEXT,
    fontSize: 14,
    fontWeight: "800",
  },
  registerScreen: {
    flex: 1,
    backgroundColor: "transparent",
  },
  registerContent: {
    padding: 24,
    paddingBottom: 40,
  },
  progressRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  progressBar: {
    flex: 1,
    height: 6,
    borderRadius: 999,
  },
  progressBarActive: {
    backgroundColor: VIOLET,
  },
  progressBarInactive: {
    backgroundColor: GLASS_SURFACE,
  },
  backGhost: {
    alignSelf: "flex-start",
    marginBottom: 16,
  },
  backButton: {
    alignSelf: "flex-start",
    padding: 10,
    backgroundColor: GLASS_SURFACE,
    borderRadius: 999,
    marginBottom: 16,
  },
  stepTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: TEXT_PRIMARY,
    marginBottom: 8,
  },
  stepSubtitle: {
    fontSize: 16,
    color: TEXT_SECONDARY,
    marginBottom: 24,
  },
  stepSubtitleSmall: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    marginBottom: 24,
  },
  phoneRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  phoneRowNoMargin: {
    flexDirection: "row",
    gap: 8,
  },
  prefixBox: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: GLASS_SURFACE,
    justifyContent: "center",
    alignItems: "center",
  },
  prefixText: {
    fontWeight: "800",
    color: TEXT_SECONDARY,
  },
  phoneInput: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: GLASS_BORDER,
    fontSize: 18,
    fontWeight: "700",
    color: TEXT_PRIMARY,
  },
  stepCenter: {
    alignItems: "center",
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: VIOLET_SURFACE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  stepTitleCenter: {
    fontSize: 28,
    fontWeight: "900",
    color: TEXT_PRIMARY,
    marginBottom: 8,
    textAlign: "center",
  },
  stepSubtitleCenter: {
    fontSize: 16,
    color: TEXT_SECONDARY,
    marginBottom: 24,
    textAlign: "center",
  },
  otpRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 24,
  },
  otpInput: {
    width: 46,
    height: 52,
    borderWidth: 2,
    borderColor: GLASS_BORDER,
    borderRadius: 14,
    textAlign: "center",
    fontSize: 22,
    fontWeight: "800",
    color: TEXT_PRIMARY,
  },
  pinInput: {
    width: "100%",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: GLASS_BORDER,
    borderRadius: 18,
    fontSize: 28,
    fontWeight: "800",
    textAlign: "center",
    color: TEXT_PRIMARY,
    marginBottom: 24,
    letterSpacing: 10,
  },
  step4Container: {
    paddingBottom: 16,
  },
  formField: {
    marginBottom: 12,
  },
  formLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: TEXT_DISABLED,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginLeft: 4,
    marginBottom: 6,
  },
  formInput: {
    width: "100%",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: GLASS_SURFACE,
    fontSize: 14,
    color: TEXT_PRIMARY,
  },
  uploadBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: GLASS_SURFACE,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
  },
  uploadIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: VIOLET_SURFACE,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  uploadTextWrap: {
    flex: 1,
  },
  uploadPrimaryText: {
    fontSize: 14,
    fontWeight: "700",
    color: TEXT_PRIMARY,
  },
  uploadSecondaryText: {
    fontSize: 12,
    color: VIOLET_TEXT,
    fontWeight: "700",
    marginTop: 2,
  },
  row2: {
    flexDirection: "row",
    gap: 12,
  },
  row3: {
    flexDirection: "row",
    gap: 12,
  },
  flex1: {
    flex: 1,
  },
  smallCol: {
    width: "28%",
  },
  largeCol: {
    flex: 1,
  },
  groupBoxGray: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 18,
    padding: 16,
  },
  groupBoxPurple: {
    backgroundColor: VIOLET_SURFACE,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: VIOLET_BORDER,
  },
  dashboardScreen: {
    flex: 1,
    backgroundColor: "transparent",
  },
  dashboardSafeTop: {
    backgroundColor: "transparent",
  },
  dashboardHeader: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: GLASS_SURFACE,
    borderBottomWidth: 1,
    borderBottomColor: GLASS_BORDER,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  kicker: {
    fontSize: 10,
    color: TEXT_DISABLED,
    fontWeight: "800",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  balance: {
    fontSize: 24,
    fontWeight: "900",
    color: TEXT_PRIMARY,
    marginTop: 2,
  },
  iconButton: {
    padding: 12,
    backgroundColor: GLASS_SURFACE,
    borderRadius: 18,
  },
  iconButtonPressed: {
    transform: [{ scale: 0.95 }],
  },
  dashboardContent: {
    padding: 24,
    paddingBottom: 40,
  },
  virtualCard: {
    width: "95%",
    aspectRatio: 1.586,
    borderRadius: 32,
    padding: 20,
    overflow: "hidden",
    marginBottom: 16,
  },
  virtualCardOn: {
    backgroundColor: VIOLET,
    shadowColor: PURPLE,
    shadowOpacity: 0.4,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  virtualCardOff: {
    backgroundColor: GLASS_SURFACE_STRONG,
  },
  virtualCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
    backgroundColor: SCRIM_SOFT,
    alignItems: "center",
    justifyContent: "center",
  },
  virtualCardOverlayText: {
    color: TEXT_PRIMARY,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 8,
    textTransform: "uppercase",
  },
  virtualCardInner: {
    flex: 1,
    justifyContent: "space-between",
    zIndex: 10,
  },
  virtualCardNumber: {
    color: TEXT_PRIMARY,
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
    letterSpacing: 4,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }),
  },
  virtualCardName: {
    color: TEXT_PRIMARY,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  cardToggleRow: {
    backgroundColor: GLASS_SURFACE,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  cardToggleText: {
    fontSize: 14,
    color: TEXT_PRIMARY,
    fontWeight: "800",
  },
  switchTrack: {
    width: 48,
    height: 28,
    borderRadius: 999,
    position: "relative",
  },
  switchThumb: {
    position: "absolute",
    top: 4,
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: GLASS_SURFACE,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: TEXT_PRIMARY,
    marginBottom: 12,
  },
  activityRow: {
    padding: 16,
    backgroundColor: GLASS_SURFACE,
    borderRadius: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  activityLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  activityIcon: {
    padding: 10,
    borderRadius: 12,
  },
  activityLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: TEXT_PRIMARY,
  },
  activityAmount: {
    fontSize: 14,
    fontWeight: "900",
    marginLeft: 12,
  },
  kycScreen: {
    flex: 1,
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  kycLogo: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: GLASS_SURFACE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  kycLogoText: {
    color: VIOLET_TEXT,
    fontSize: 40,
    fontWeight: "900",
    fontStyle: "italic",
  },
  kycTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: TEXT_PRIMARY,
    marginBottom: 12,
    textAlign: "center",
  },
  kycSubtitle: {
    fontSize: 16,
    color: TEXT_DISABLED,
    marginBottom: 28,
    textAlign: "center",
  },
  kycButton: {
    backgroundColor: GLASS_SURFACE,
  },
  kycButtonText: {
    color: TEXT_PRIMARY,
  },
  pageScreen: {
    flex: 1,
    backgroundColor: "transparent",
  },
  pageContent: {
    padding: 24,
    paddingBottom: 40,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: TEXT_PRIMARY,
    marginBottom: 8,
  },
  pageSubtitle: {
    fontSize: 15,
    color: TEXT_SECONDARY,
    marginBottom: 24,
  },
  statusCard: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  statusIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: VIOLET_SURFACE,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  statusTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: TEXT_PRIMARY,
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    marginBottom: 16,
    lineHeight: 20,
  },
  statusInfoBox: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 16,
    padding: 14,    
  },
  statusInfoLabel: {
    fontSize: 11,
    color: TEXT_DISABLED,
    fontWeight: "900",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  statusInfoValue: {
    fontSize: 14,
    color: TEXT_PRIMARY,
    fontWeight: "700",
  },
  centerCard: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  successBanner: {
    backgroundColor: SUCCESS_SURFACE,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: SUCCESS_BORDER,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  successTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: SUCCESS,
    marginBottom: 4,
  },
  successText: {
    fontSize: 13,
    color: SUCCESS,
    lineHeight: 18,
  },
  walletCard: {
    backgroundColor: VIOLET,
    borderRadius: 24,
    padding: 20,
    marginBottom: 15,
  },
  walletRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  },
  walletTitle: {
    color: TEXT_PRIMARY,
    fontSize: 15,
    fontWeight: "800",
  },
  walletIdText: {
    color: TEXT_PRIMARY,
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 18,
  },
  walletFundsLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  walletFundsValue: {
    color: TEXT_PRIMARY,
    fontSize: 30,
    fontWeight: "900",
  },
  transferCard: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
    padding: 18,
  },
  transferSuccessBox: {
    marginTop: 12,
    backgroundColor: SUCCESS_SURFACE,
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  transferSuccessText: {
    color: SUCCESS,
    fontWeight: "700",
    fontSize: 13,
  },
  filterWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  filterChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: GLASS_SURFACE,
  },
  filterChipActive: {
    backgroundColor: VIOLET,
  },
  filterChipText: {
    color: TEXT_SECONDARY,
    fontWeight: "700",
    fontSize: 13,
  },
  filterChipTextActive: {
    color: TEXT_PRIMARY,
  },
  operationBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  operationBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: TEXT_PRIMARY,
  },
  operationDate: {
    fontSize: 11,
    color: TEXT_DISABLED,
    fontWeight: "700",
    marginTop: 4,
  },
  emptyCard: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 18,
    padding: 18,
    alignItems: "center",
  },
  emptyCardText: {
    color: TEXT_SECONDARY,
    fontWeight: "700",
  },
  profileAvatarWrap: {
    alignItems: "center",
    marginBottom: 20,
  },
  profileAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: GLASS_SURFACE_STRONG,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 4,
    borderColor: GLASS_BORDER,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: SCRIM,
  },
  drawer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: 288,
    backgroundColor: GLASS_SURFACE,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: -6, height: 0 },
    elevation: 12,
  },
  drawerContent: {
    flex: 1,
    padding: 24,
  },
  drawerClose: {
    alignSelf: "flex-start",
    padding: 10,
    backgroundColor: GLASS_SURFACE,
    borderRadius: 14,
    marginBottom: 24,
  },
  drawerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 8,
  },
  drawerItemText: {
    fontSize: 16,
    fontWeight: "800",
    color: TEXT_PRIMARY,
  },
  drawerLogoutText: {
    fontSize: 16,
    fontWeight: "800",
    color: DANGER,
  },
  spacer: {
    flex: 1,
  },
  stack12: {
    gap: 12,
  },
  stack16: {
    gap: 16,
  },
  stack24: {
    gap: 24,
  },
  beneficiaryCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: GLASS_SURFACE,
    borderWidth: 1,
    borderColor: GLASS_BORDER,
  },
  beneficiaryCardSelected: {
    backgroundColor: VIOLET,
    borderColor: VIOLET,
  },
  beneficiaryIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: VIOLET_SURFACE,
    alignItems: "center",
    justifyContent: "center",
  },
  beneficiaryName: {
    fontSize: 14,
    fontWeight: "900",
    color: TEXT_PRIMARY,
  },
  beneficiaryNameSelected: {
    color: TEXT_PRIMARY,
  },
  beneficiaryMeta: {
    fontSize: 12,
    fontWeight: "600",
    color: TEXT_SECONDARY,
    marginTop: 2,
  },
  beneficiaryMetaSelected: {
    color: "rgba(255,255,255,0.8)",
  },
  errorBox: {
    marginTop: 12,
    backgroundColor: DANGER_SURFACE,
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    color: DANGER,
    fontWeight: "700",
    fontSize: 13,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: TEXT_PRIMARY,
    marginBottom: 24,
  },
  card: {
    backgroundColor: GLASS_SURFACE,
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  row: {
    marginBottom: 18,
  },
  label: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    marginBottom: 4,
  },
  value: {
    fontSize: 18,
    fontWeight: "600",
    color: TEXT_PRIMARY,
  },
  cancelButton: {
    marginTop: 30,
    backgroundColor: DANGER_SOLID,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
  },

  cancelButtonText: {
    color: TEXT_PRIMARY,
    fontSize: 16,
    fontWeight: "700",
  },

  cardSlide: {
  width: Dimensions.get("window").width - 40,
  marginRight: 0,
},

cardTypeLabel: {
  fontSize: 14,
  fontWeight: "600",
  marginBottom: 8,
  color: TEXT_PRIMARY,
},

dotsRow: {
  flexDirection: "row",
  justifyContent: "center",
  alignItems: "center",
  gap: 6,
  marginTop: 12,
  marginBottom: 16,
},

dot: {
  width: 8,
  height: 8,
  borderRadius: 4,
  backgroundColor: GLASS_SURFACE_STRONG,
},

dotActive: {
  width: 18,
  backgroundColor: VIOLET,
},
inactiveCardMessage: {
  backgroundColor: WARNING_SURFACE,
  borderRadius: 14,
  padding: 14,
  marginBottom: 14,
},

inactiveCardTitle: {
  fontSize: 14,
  fontWeight: "700",
  color: WARNING,
  marginBottom: 4,
},

activateNowText: {
  fontSize: 14,
  fontWeight: "700",
  color: VIOLET_TEXT,
},

successCardMessage: {
  backgroundColor: SUCCESS_SURFACE,
  borderRadius: 14,
  padding: 14,
  marginBottom: 14,
},

successCardText: {
  fontSize: 14,
  fontWeight: "700",
  color: SUCCESS,
},

modalOverlay: {
  flex: 1,
  backgroundColor: SCRIM,
  justifyContent: "center",
  alignItems: "center",
  padding: 24,
},

modalContent: {
  width: "100%",
  backgroundColor: GLASS_SURFACE,
  borderRadius: 20,
  padding: 20,
},

modalTitle: {
  fontSize: 18,
  fontWeight: "700",
  color: TEXT_PRIMARY,
  marginBottom: 6,
},

modalSubtitle: {
  fontSize: 14,
  color: TEXT_SECONDARY,
  marginBottom: 16,
},

secureCodeInput: {
  height: 52,
  borderWidth: 1,
  borderColor: GLASS_BORDER,
  borderRadius: 12,
  paddingHorizontal: 16,
  fontSize: 16,
  letterSpacing: 6,
  textAlign: "center",
  marginBottom: 16,
},

activateButton: {
  height: 48,
  borderRadius: 12,
  backgroundColor: VIOLET,
  alignItems: "center",
  justifyContent: "center",
  marginBottom: 14,
},

activateButtonDisabled: {
  opacity: 0.5,
},

activateButtonText: {
  color: TEXT_PRIMARY,
  fontSize: 15,
  fontWeight: "700",
},

cancelText: {
  textAlign: "center",
  color: TEXT_SECONDARY,
  fontSize: 14,
  fontWeight: "600",
},

selectField: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  width: "100%",
  paddingVertical: 12,
  paddingHorizontal: 14,
  borderRadius: 14,
  backgroundColor: GLASS_SURFACE,
},
selectFieldText: {
  fontSize: 14,
  color: TEXT_PRIMARY,
},
selectFieldPlaceholder: {
  fontSize: 14,
  color: TEXT_DISABLED,
},
pickerOverlay: {
  flex: 1,
  backgroundColor: SCRIM,
  justifyContent: "flex-end",
},
modalSheet: {
  backgroundColor: GLASS_SURFACE,
  borderTopLeftRadius: 24,
  borderTopRightRadius: 24,
  padding: 20,
  maxHeight: "70%",
},
pickerTitle: {
  fontSize: 16,
  fontWeight: "800",
  color: TEXT_PRIMARY,
  marginBottom: 12,
},
modalScroll: {
  marginBottom: 8,
},
modalOption: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  paddingVertical: 14,
  borderBottomWidth: 1,
  borderBottomColor: GLASS_BORDER,
},
modalOptionText: {
  fontSize: 15,
  color: TEXT_PRIMARY,
},

fieldErrorText: {
  color: DANGER,
  fontSize: 12,
  marginTop: 4,
  marginLeft: 4,
},

fieldHintText: {
  color: TEXT_SECONDARY,
  fontSize: 12,
  marginTop: 4,
  marginLeft: 4,
},
prefixBoxRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 4,
},

documentCard: {
  borderWidth: 1,
  borderColor: GLASS_BORDER,
  borderRadius: 16,
  backgroundColor: GLASS_SURFACE,
  padding: 12,
  gap: 8,
},
documentCardLabel: {
  fontSize: 13,
  fontWeight: "700",
  color: TEXT_PRIMARY,
},
documentRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 12,
},
documentEmptyRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 12,
},
documentThumb: {
  width: 64,
  height: 64,
  borderRadius: 12,
  backgroundColor: GLASS_SURFACE,
},
documentThumbFile: {
  alignItems: "center",
  justifyContent: "center",
  gap: 2,
},
documentThumbEmpty: {
  width: 64,
  height: 64,
  borderRadius: 12,
  backgroundColor: VIOLET_SURFACE,
  alignItems: "center",
  justifyContent: "center",
  borderWidth: 1,
  borderColor: VIOLET_BORDER,
  borderStyle: "dashed",
},
documentThumbBadge: {
  fontSize: 10,
  fontWeight: "800",
  color: VIOLET_TEXT,
},
documentInfo: {
  flex: 1,
  gap: 2,
},
documentName: {
  fontSize: 14,
  fontWeight: "600",
  color: TEXT_PRIMARY,
},
documentMeta: {
  fontSize: 12,
  color: TEXT_SECONDARY,
},
documentStatusRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 6,
  marginTop: 2,
},
documentOkText: {
  fontSize: 12,
  color: SUCCESS,
  fontWeight: "600",
},
documentErrorText: {
  flex: 1,
  fontSize: 12,
  color: DANGER,
},
documentActions: {
  gap: 8,
},
documentActionButton: {
  width: 34,
  height: 34,
  borderRadius: 10,
  backgroundColor: GLASS_SURFACE,
  alignItems: "center",
  justifyContent: "center",
},
documentRetry: {
  alignSelf: "flex-start",
  paddingVertical: 6,
  paddingHorizontal: 10,
  borderRadius: 10,
  backgroundColor: DANGER_SURFACE,
},
documentRetryText: {
  fontSize: 12,
  fontWeight: "700",
  color: DANGER,
},

verifyingWrap: {
  alignItems: "center",
  justifyContent: "center",
  paddingHorizontal: 24,
  paddingVertical: 90,
  gap: 14,
},
credentialsCard: {
  width: "100%",
  borderWidth: 1,
  borderColor: GLASS_BORDER,
  borderRadius: 18,
  backgroundColor: GLASS_SURFACE,
  padding: 16,
  gap: 14,
},
credentialsLabel: {
  fontSize: 12,
  fontWeight: "700",
  color: TEXT_SECONDARY,
  textTransform: "uppercase",
},
credentialsValue: {
  fontSize: 17,
  fontWeight: "700",
  color: TEXT_PRIMARY,
},
credentialsValueRow: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 12,
},
credentialsToggleText: {
  fontSize: 13,
  fontWeight: "700",
  color: VIOLET_TEXT,
},
successIconCircle: {
  width: 78,
  height: 78,
  borderRadius: 39,
  backgroundColor: SUCCESS_SURFACE,
  alignItems: "center",
  justifyContent: "center",
},
fieldHighlighted: {
  borderWidth: 2,
  borderColor: DANGER_BORDER,
  backgroundColor: DANGER_SURFACE,
},
selectFieldDisabled: {
  backgroundColor: GLASS_SURFACE,
  opacity: 0.6,
},
selectFieldDisabledText: {
  fontSize: 14,
  color: TEXT_DISABLED,
},
searchRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 8,
  paddingHorizontal: 12,
  paddingVertical: 10,
  borderRadius: 12,
  backgroundColor: GLASS_SURFACE,
  marginBottom: 8,
},
searchInput: {
  flex: 1,
  fontSize: 14,
  color: TEXT_PRIMARY,
  paddingVertical: 0,
},
emptyResultsText: {
  paddingVertical: 24,
  textAlign: "center",
  color: TEXT_SECONDARY,
  fontSize: 14,
},
formBanner: {
  flexDirection: "row",
  alignItems: "center",
  gap: 8,
  padding: 12,
  borderRadius: 14,
  backgroundColor: DANGER_SURFACE,
  borderWidth: 1,
  borderColor: DANGER_BORDER,
},
formBannerText: {
  flex: 1,
  color: DANGER,
  fontSize: 13,
  lineHeight: 18,
},

otpActionsRow: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  gap: 16,
  marginBottom: 8,
},
resendText: {
  fontSize: 13,
  color: TEXT_SECONDARY,
},
resendLink: {
  fontSize: 13,
  color: VIOLET_TEXT,
  fontWeight: "800",
},
pasteLink: {
  fontSize: 13,
  color: VIOLET_TEXT,
  fontWeight: "800",
},

passcodeFieldWrap: {
  width: "100%",
  position: "relative",
  marginBottom: 8,
},
eyeToggle: {
  position: "absolute",
  right: 16,
  top: 0,
  bottom: 0,
  justifyContent: "center",
},

forgotLink: {
  alignSelf: "center",
  marginTop: 4,
},
forgotLinkText: {
  fontSize: 13,
  color: VIOLET_TEXT,
  fontWeight: "700",
},

infoBox: {
  backgroundColor: VIOLET_SURFACE,
  borderRadius: 16,
  padding: 16,
  marginBottom: 24,
},
infoBoxText: {
  fontSize: 14,
  color: TEXT_SECONDARY,
  lineHeight: 20,
},
});